/*
 * Generated by orval v5.3.2 🍺
 * Do not edit manually.
 * API modeles-vehicules
 * Cette API permet de gérer le référentiel des véhicules (modèle générique).<br> Un véhicule peut être de type auto, moto, quad, cyclo ou camping-car.<br> L'API permet d'exposer (recherche, consultation) des données spécifiques à chaque type de véhicules (par exemple le nombre de portes pour un véhicule de type auto) ou communes à tous les types de véhicules (par exemple recherche d'un véhicule par immatriculation).

 * OpenAPI spec version: 1.6.5
 */
export interface AvertissementDTO {
	code?: string
	message?: string
}

export interface CarrosserieVehicule {
	codeCarrosserie: string
	libelleCarrosserie: string
}

export interface ChassisVehicule {
	libelleMarqueChassis: string
	libelleFamilleChassis: string
}

export interface EnergieVehicule {
	codeEnergie: string
	libelleEnergie: string
}

export interface FamilleCelluleVehicule {
	libelleFamilleCellule: string
}

export interface FamilleVehicule {
	codeFamille: string
	libelleFamille: string
}

export interface FamilleVehiculeDTO {
	libelleLongFamilleVehicule?: string
	numeroIdentifiantFamille?: string
}

export interface GroupeTarificationVehicule {
	codeGroupeTarificationAM1: string
	libelleGroupeTarificationAM1: string
	codeGroupeTarification: string
	libelleGroupeTarification: string
	codeGroupeTarificationAP1: string
	libelleGroupeTarificationAP1: string
}

export interface InfoPagination {
	page: number
	totalPages: number
	nombreElements: number
	totalElements: number
	premierePage: boolean
	dernierePage: boolean
	taillePage: number
	triPagination: TriPagination[]
}

export interface InfoSraVehPost {
	codeSra: string
	numeroRepertoire?: string
}

export interface InfoSraVehPut {
	codeSra: string
	numeroRepertoire?: string
}

export interface MarqueVehicule {
	codeMarque: string
	libelleMarque: string
}

export interface MarqueVehiculeDTO {
	libelleMarque?: string
	numeroIdentifiantMRQ?: string
}

export interface ModelVehDTOLight {
	modeleVehicule?: ModeleVehPDDLight
}

export interface ModeleVehPDDLight {
	codeGroupeTarification?: string
	libelleFamilleVehicule?: string
	libelleMarque?: string
	numeroRepertoireVehicule?: string
}

export interface ModeleVehicule {
	anneeDateDebutFabrication?: number
	anneeDateFinFabrication?: number
	champRechercheVehicule?: string
	codeCarrosserieVehicule?: number
	codeCategorieVehicule?: number
	codeDegreAutonomie?: string
	codeEnergieVehicule?: number
	codeGenreVehicule?: string
	codeGestionVehicule?: number
	codeGroupeTarification?: string
	codeInterditNovice?: number
	codeNiveauFinitionVehicule?: string
	codeSegmentVehicule?: string
	codeVocationVehicule?: string
	dateDebutFabrication?: string
	dateFinFabrication?: string
	denominationCommercialeCourte?: string
	denominationCommercialeLongue?: string
	libelleEnergieVehicule?: string
	libelleFamilleVehicule?: string
	libelleGenerationModeleVehicule?: string
	libelleGenreVehicule?: string
	libelleGestionVehicule?: string
	libelleInterditNovice?: string
	libelleLongCarrosserieVehicule?: string
	libelleLongTransmissionVehicule?: string
	libelleMarque?: string
	libelleMotorisationVehicule?: string
	libelleNiveauFinitionVehicule?: string
	libelleObservationLong?: string
	libelleSegmentVehicule?: string
	libelleVocationVehicule?: string
	nombrePorte?: number
	numeroRepertoireVehicule?: string
	puissanceFiscale?: number
	puissanceVehicule?: number
	sraVehicules?: SraVehiculePDD[]
	typeTransmissionVehicule?: number
}

export interface MotorisationVehicule {
	libelleMotorisation: string
}

export interface NiveauFinitionVehicule {
	libelleNiveauFinition: string
}

export interface NombrePortesVehicule {
	nombrePortes: string
}

export interface PuissanceFiscaleVehicule {
	puissanceFiscale: string
}

// tslint:disable-next-line:no-empty-interface
export interface Sort {}

export interface Sra {
	codeEtatSraVehicule: string
	libelleEtatSraVehicule: string
	codeSra: string
	numeroRepertoire?: string
	dateMiseAJour: string
}

export interface SraPagination {
	infoPagination: InfoPagination
	sraDemandes: Sra[]
}

export interface SraVehDto {
	cetaSraVeh?: string
	codeSraVeh?: string
	dateMaj?: string
	idSraVeh?: number
	numRepVeh?: string
}

export interface SraVehiculePDD {
	codeEtat?: string
	codeSRAVehicule?: string
	numeroIdentifiantSRAVEH?: number
	numeroRepertoireVehicule?: string
}

export interface TransmissionVehicule {
	codeTransmission: string
	libelleTransmission: string
}

export interface TriPagination {
	direction?: string
	property?: string
	ignoreCase?: boolean
	nullHandling?: string
	descending?: boolean
	ascending?: boolean
}

export interface VehiculeAssureDTO {
	avertissements?: AvertissementDTO[]
	dateMEC?: string
	immatriculation?: string
	modelesVeh?: ModeleVehicule[]
}

export interface VehiculeDetail {
	numeroRepertoire: string
	codeMarque: string
	libelleMarque: string
	codeCategorie: string
	codeCategorieOrigine?: string
	libelleCategorieOrigine?: string
	codeFamille: string
	libelleFamille: string
	nombrePortes?: string
	typeMotorisation: string
	libelleMotorisation?: string
	codeEnergie?: string
	libelleEnergie?: string
	codeTransmission?: string
	libelleTransmission?: string
	puissanceFiscale?: string
	cylindre?: string
	codeCarrosserie?: string
	libelleCarrosserie?: string
	denominationCommercialeCourte: string
	denominationCommercialeLongue: string
	codeAssujettissementClause: string
	libelleAssujettissementClause: string
	codeNiveauFinition: string
	libelleNiveauFinition: string
	libelleFamilleCellule?: string
	libelleMarqueChassis?: string
	libelleFamilleChassis: string
	libelleTypeMineTasse: string
	codeSituationModele: string
	libelleSituationModele: string
	dateDebutFabrication?: string
	dateFinFabrication?: string
	codeDegreAutonomie: string
	libelleObservationLong: string
	champRecherche: string
	codeGenre: string
	libelleGenre: string
	codeGestion?: string
	libelleGestion?: string
	codeInterditNovice?: string
	libelleInterditNovice?: string
	codeSegment?: string
	libelleSegment?: string
	codeVocation?: string
	libelleVocation?: string
	codeGroupeTarification: string
	poidsAVide?: number
	puissance?: string
	libelleGenerationModele?: string
}

export interface VehiculeSynthese {
	numeroRepertoire: string
	denominationCommerciale: string
	denominationCommercialeLongue?: string
	lienDetailVehicule: string
}

export interface PageSraVehDto {
	content?: SraVehDto[]
	first?: boolean
	last?: boolean
	number?: number
	numberOfElements?: number
	size?: number
	sort?: Sort
	totalElements?: number
	totalPages?: number
}

export type SraVehDtoBody = SraVehDto

export type RecupererListeSRAParams = {
	codeSra?: string
	codeEtatSraVehicule?: string
	numeroRepertoire?: string
	page?: number
	taillePage?: number
}

export type GetSraWithCodeEtatUsingGETParams = {
	codeEtatSRAVEH?: string
	codeSRAVEH?: string
	numeroRepertoire?: string
	page?: number
	size?: number
}

export type GetFamillesUsingGETParams = {
	categorieVehicule: string
	marquesId: string
}

export type GetNumRepForImmatriculationUsingGETParams = {
	immatriculation: string
}

export type GetMarquesUsingGETParams = { categorieVehicule: string }

export type GetNumeroRepertoiresVehiculesUsingGETParams = {
	numeroRepertoireVehicule?: string
}

export type GetModleVehiculesByNumeroChassisUsingGETParams = {
	numero_chassis: string
}

export type GetNumRepForImmatriculationUsingGET1Params = {
	immatriculation: string
}

export type GetModleVehiculesByNumeroChassisUsingGET1Params = {
	numero_chassis: string
}

export type RecupererListeAutosParams = {
	listeCodesCategorie?: string[]
	listeCodesMarque?: string[]
	listeAnneesCirculation?: number[]
	listeCodesFamille?: string[]
	listeCodesEnergie?: string[]
	listeNombresPortes?: string[]
	listeCodesTransmission?: string[]
	listeLibellesMotorisation?: string[]
	listeCodesCarrosserie?: string[]
}

export type RecupererListeCarrosseriesAutosParams = {
	listeCodesCategorie?: string[]
	listeCodesMarque?: string[]
	listeAnneesCirculation?: number[]
	listeCodesFamille?: string[]
	listeCodesEnergie?: string[]
	listeNombresPortes?: string[]
	listeCodesTransmission?: string[]
	listeLibellesMotorisation?: string[]
}

export type RecupererListeEnergiesAutosParams = {
	listeCodesCategorie?: string[]
	listeCodesMarque?: string[]
	listeAnneesCirculation?: number[]
	listeCodesFamille?: string[]
	listeNombresPortes?: string[]
	listeCodesTransmission?: string[]
	listeLibellesMotorisation?: string[]
	listeCodesCarrosserie?: string[]
}

export type RecupererListeFamillesAutosParams = {
	listeCodesCategorie?: string[]
	listeCodesMarque?: string[]
	listeAnneesCirculation?: number[]
	listeCodesEnergie?: string[]
	listeNombresPortes?: string[]
	listeCodesTransmission?: string[]
	listeLibellesMotorisation?: string[]
	listeCodesCarrosserie?: string[]
}

export type RecupererListeGroupesTarifAutosParams = {
	listeCodesCategorie?: string[]
	listeCodesMarque?: string[]
	listeAnneesCirculation?: number[]
	listeCodesFamille?: string[]
	listeCodesEnergie?: string[]
	listeNombresPortes?: string[]
	listeCodesTransmission?: string[]
	listeLibellesMotorisation?: string[]
	listeCodesCarrosserie?: string[]
	listeDenominationsCommerciales?: string[]
}

export type RecupererListeMarquesAutosParams = {
	listeCodesCategorie?: string[]
	listeAnneesCirculation?: number[]
	listeCodesFamille?: string[]
	listeCodesEnergie?: string[]
	listeNombresPortes?: string[]
	listeCodesTransmission?: string[]
	listeLibellesMotorisation?: string[]
	listeCodesCarrosserie?: string[]
}

export type RecupererListeMotorisationsAutosParams = {
	listeCodesCategorie?: string[]
	listeCodesMarque?: string[]
	listeAnneesCirculation?: number[]
	listeCodesFamille?: string[]
	listeCodesEnergie?: string[]
	listeNombresPortes?: string[]
	listeCodesTransmission?: string[]
	listeCodesCarrosserie?: string[]
}

export type RecupererListeNbPortesAutosParams = {
	listeCodesCategorie?: string[]
	listeCodesMarque?: string[]
	listeAnneesCirculation?: number[]
	listeCodesFamille?: string[]
	listeCodesEnergie?: string[]
	listeCodesTransmission?: string[]
	listeLibellesMotorisation?: string[]
	listeCodesCarrosserie?: string[]
}

export type RecupererListeTransmissionsAutosParams = {
	listeCodesCategorie?: string[]
	listeCodesMarque?: string[]
	listeAnneesCirculation?: number[]
	listeCodesFamille?: string[]
	listeCodesEnergie?: string[]
	listeNombresPortes?: string[]
	listeLibellesMotorisation?: string[]
	listeCodesCarrosserie?: string[]
}

export type RecupererListeCampingCarsParams = {
	listeCodesCategorie?: string[]
	listeCodesMarqueCellule?: string[]
	listeAnneesCirculation?: number[]
	listeLibellesFamilleCellule?: string[]
	listeCodesCarrosserie?: string[]
	listeLibellesNiveauFinition?: string[]
	listeLibellesMarqueChassis?: string[]
	listeLibellesFamilleChassis?: string[]
	listeCodesEnergie?: string[]
	listePuissancesFiscales?: string[]
}

export type RecupererListeCarrosseriesCampingCarsParams = {
	listeCodesCategorie?: string[]
	listeCodesMarqueCellule?: string[]
	listeAnneesCirculation?: number[]
	listeLibellesFamilleCellule?: string[]
	listeLibellesNiveauFinition?: string[]
	listeLibellesMarqueChassis?: string[]
	listeLibellesFamilleChassis?: string[]
	listeCodesEnergie?: string[]
	listePuissancesFiscales?: string[]
}

export type RecupererListeChassisCampingCarsParams = {
	listeCodesCategorie?: string[]
	listeCodesMarqueCellule?: string[]
	listeAnneesCirculation?: number[]
	listeLibellesFamilleCellule?: string[]
	listeCodesCarrosserie?: string[]
	listeLibellesNiveauFinition?: string[]
	listeCodesEnergie?: string[]
	listePuissancesFiscales?: string[]
}

export type RecupererListeEnergiesCampingCarsParams = {
	listeCodesCategorie?: string[]
	listeCodesMarqueCellule?: string[]
	listeAnneesCirculation?: number[]
	listeLibellesFamilleCellule?: string[]
	listeCodesCarrosserie?: string[]
	listeLibellesNiveauFinition?: string[]
	listeLibellesMarqueChassis?: string[]
	listeLibellesFamilleChassis?: string[]
	listePuissancesFiscales?: string[]
}

export type RecupererListeFamillesCampingCarsParams = {
	listeCodesCategorie?: string[]
	listeCodesMarqueCellule?: string[]
	listeAnneesCirculation?: number[]
	listeCodesCarrosserie?: string[]
	listeLibellesNiveauFinition?: string[]
	listeLibellesMarqueChassis?: string[]
	listeLibellesFamilleChassis?: string[]
	listeCodesEnergie?: string[]
	listePuissancesFiscales?: string[]
}

export type RecupererListeMarquesCampingCarsParams = {
	listeCodesCategorie?: string[]
	listeAnneesCirculation?: number[]
	listeLibellesFamilleCellule?: string[]
	listeCodesCarrosserie?: string[]
	listeLibellesNiveauFinition?: string[]
	listeLibellesMarqueChassis?: string[]
	listeLibellesFamilleChassis?: string[]
	listeCodesEnergie?: string[]
	listePuissancesFiscales?: string[]
}

export type RecupererListeFinitionsCampingCarsParams = {
	listeCodesCategorie?: string[]
	listeCodesMarqueCellule?: string[]
	listeAnneesCirculation?: number[]
	listeLibellesFamilleCellule?: string[]
	listeCodesCarrosserie?: string[]
	listeLibellesMarqueChassis?: string[]
	listeLibellesFamilleChassis?: string[]
	listeCodesEnergie?: string[]
	listePuissancesFiscales?: string[]
}

export type RecupererListePuissancesCampingCarsParams = {
	listeCodesCategorie?: string[]
	listeCodesMarqueCellule?: string[]
	listeAnneesCirculation?: number[]
	listeLibellesFamilleCellule?: string[]
	listeCodesCarrosserie?: string[]
	listeLibellesNiveauFinition?: string[]
	listeLibellesMarqueChassis?: string[]
	listeLibellesFamilleChassis?: string[]
	listeCodesEnergie?: string[]
}

export type RecupererListeCyclosParams = {
	listeCodesCategorie?: string[]
	listeCodesMarque?: string[]
	listeAnneesCirculation?: number[]
	listeCodesFamille?: string[]
}

export type RecupererListeFamillesCyclosParams = {
	listeCodesCategorie?: string[]
	listeCodesMarque?: string[]
	listeAnneesCirculation?: number[]
	listeCodesGenre?: string[]
}

export type RecupererListeGroupesTarifCyclosParams = {
	listeCodesCategorie?: string[]
	listeCodesMarque?: string[]
	listeAnneesCirculation?: number[]
	listeCodesFamille?: string[]
	listeDenominationsCommerciales?: string[]
}

export type RecupererListeMarquesCyclosParams = {
	listeCodesCategorie?: string[]
	listeAnneesCirculation?: number[]
	listeCodesFamille?: string[]
}

export type RecupererListeMotosQuadParams = {
	listeCodesCategorie?: string[]
	typeVehicule?: RecupererListeMotosQuadTypeVehicule
	listeCodesMarque?: string[]
	listeAnneesCirculation?: number[]
	listeCodesFamille?: string[]
	listeCodesCarrosserie?: string[]
}

export type RecupererListeMotosQuadTypeVehicule = "MOTO" | "QUAD"

export const RecupererListeMotosQuadTypeVehicule = {
	MOTO: "MOTO" as RecupererListeMotosQuadTypeVehicule,
	QUAD: "QUAD" as RecupererListeMotosQuadTypeVehicule,
}

export type RecupererListeCarrosseriesMotosQuadParams = {
	listeCodesCategorie?: string[]
	typeVehicule?: RecupererListeCarrosseriesMotosQuadTypeVehicule
	listeCodesMarque?: string[]
	listeAnneesCirculation?: number[]
	listeCodesFamille?: string[]
}

export type RecupererListeCarrosseriesMotosQuadTypeVehicule = "MOTO" | "QUAD"

export const RecupererListeCarrosseriesMotosQuadTypeVehicule = {
	MOTO: "MOTO" as RecupererListeCarrosseriesMotosQuadTypeVehicule,
	QUAD: "QUAD" as RecupererListeCarrosseriesMotosQuadTypeVehicule,
}

export type RecupererListeFamillesMotosQuadParams = {
	listeCodesCategorie?: string[]
	typeVehicule?: RecupererListeFamillesMotosQuadTypeVehicule
	listeCodesMarque?: string[]
	listeAnneesCirculation?: number[]
	listeCodesCarrosserie?: string[]
}

export type RecupererListeFamillesMotosQuadTypeVehicule = "MOTO" | "QUAD"

export const RecupererListeFamillesMotosQuadTypeVehicule = {
	MOTO: "MOTO" as RecupererListeFamillesMotosQuadTypeVehicule,
	QUAD: "QUAD" as RecupererListeFamillesMotosQuadTypeVehicule,
}

export type RecupererListeGroupesTarifMotosQuadParams = {
	listeCodesCategorie?: string[]
	typeVehicule?: RecupererListeGroupesTarifMotosQuadTypeVehicule
	listeCodesMarque?: string[]
	listeAnneesCirculation?: number[]
	listeCodesFamille?: string[]
	listeCodesCarrosserie?: string[]
	listeDenominationsCommerciales?: string[]
}

export type RecupererListeGroupesTarifMotosQuadTypeVehicule = "MOTO" | "QUAD"

export const RecupererListeGroupesTarifMotosQuadTypeVehicule = {
	MOTO: "MOTO" as RecupererListeGroupesTarifMotosQuadTypeVehicule,
	QUAD: "QUAD" as RecupererListeGroupesTarifMotosQuadTypeVehicule,
}

export type RecupererListeMarquesMotosQuadParams = {
	listeCodesCategorie?: string[]
	typeVehicule?: RecupererListeMarquesMotosQuadTypeVehicule
	listeAnneesCirculation?: number[]
	listeCodesFamille?: string[]
	listeCodesCarrosserie?: string[]
}

export type RecupererListeMarquesMotosQuadTypeVehicule = "MOTO" | "QUAD"

export const RecupererListeMarquesMotosQuadTypeVehicule = {
	MOTO: "MOTO" as RecupererListeMarquesMotosQuadTypeVehicule,
	QUAD: "QUAD" as RecupererListeMarquesMotosQuadTypeVehicule,
}
