/*
 * Generated by orval v5.3.2 🍺
 * Do not edit manually.
 * iard-devis-vehicules-v1
 * "Cette API permet de gÃ©rer le contexte iard-devis-vehicules."
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */
import axios,{
  AxiosRequestConfig
} from 'axios'
import {
  useMutation,
  UseMutationOptions
} from 'react-query'
import type {
  InfoEditionDevisBody
} from './iard-devis-vehicules-v1.schemas'
import {
  rest
} from 'msw'


type AsyncReturnType<
T extends (...args: any) => Promise<any>
> = T extends (...args: any) => Promise<infer R> ? R : any;


export const lancerCreationEditionDevisMail = <Data = unknown>(
    infoEditionDevisBody: InfoEditionDevisBody, options?: AxiosRequestConfig
 ) => {
    return axios.post<Data extends unknown ? unknown : Data>(
      `/devis/editions/mail`,
      infoEditionDevisBody,options
    );
  }



    export const useLancerCreationEditionDevisMail = <
      Data extends unknown = unknown,
      Error extends unknown = unknown
    >(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof lancerCreationEditionDevisMail>, Error, {data: InfoEditionDevisBody}, unknown>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      return useMutation<AsyncReturnType<typeof lancerCreationEditionDevisMail>, Error, {data: InfoEditionDevisBody}>((props) => {
        const {data} = props || {};

        return  lancerCreationEditionDevisMail<Data>(data,axiosOptions)
      }, mutationOptions)
    }
    export const lancerCreationEditionDevisPdf = <Data = unknown>(
    infoEditionDevisBody: InfoEditionDevisBody, options?: AxiosRequestConfig
 ) => {
    return axios.post<Data extends unknown ? string : Data>(
      `/devis/editions/pdf`,
      infoEditionDevisBody,options
    );
  }



    export const useLancerCreationEditionDevisPdf = <
      Data extends unknown = unknown,
      Error extends unknown = unknown
    >(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof lancerCreationEditionDevisPdf>, Error, {data: InfoEditionDevisBody}, unknown>, axios?: AxiosRequestConfig}
) => {
      const {mutation: mutationOptions, axios: axiosOptions} = options || {}

      return useMutation<AsyncReturnType<typeof lancerCreationEditionDevisPdf>, Error, {data: InfoEditionDevisBody}>((props) => {
        const {data} = props || {};

        return  lancerCreationEditionDevisPdf<Data>(data,axiosOptions)
      }, mutationOptions)
    }
    

export const getEditionsMSW = () => [
rest.post('*/devis/editions/mail', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
        )
      }),rest.post('*/devis/editions/pdf', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
        )
      }),]
